In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/kevinnumanzor17/etl-data-pipeline-2522192022/refs/heads/main/data/raw/B_inventario.csv"

df = pd.read_csv(url)

df.head()

  id_inventario id_producto stock      bodega
0         I7000      PR1115   165    Tránsito
1         I7001      PR1031   236  Sucursal 1
2         I7002      PR1129    40  Sucursal 2
3         I7003      PR1083    61     Central
4         I7004      PR1021   245     Central

In [4]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_inventario  186 non-null    object
 1   id_producto    180 non-null    object
 2   stock          181 non-null    object
 3   bodega         186 non-null    object
dtypes: object(4)
memory usage: 5.9+ KB

id_inventario    0
id_producto      6
stock            5
bodega           0
dtype: int64

In [5]:
import pandas as pd

inventario = df.copy()

# limpiar nombres de columnas
inventario.columns = inventario.columns.str.strip().str.lower()

# limpiar espacios
for col in inventario.select_dtypes(include='object').columns:
 inventario[col] = inventario[col].astype(str).str.strip()

# convertir vacíos en null
inventario = inventario.replace(r'^\s*$', pd.NA, regex=True)

# eliminar duplicados
inventario = inventario.drop_duplicates()

In [6]:
# convertir id a número
inventario['id_inventario'] = pd.to_numeric(
inventario['id_inventario'],
errors='coerce'
)

# convertir stock a número
inventario['stock'] = pd.to_numeric(
inventario['stock'],
errors='coerce'
)

# normalizar bodega
inventario['bodega'] = inventario['bodega'].str.strip().str.title()

In [7]:
validos = inventario[
inventario['id_inventario'].notna() &
inventario['id_producto'].notna() &
inventario['stock'].notna() &
inventario['bodega'].notna()
].copy()

rechazados = inventario[
inventario['id_inventario'].isna() |
inventario['id_producto'].isna() |
inventario['stock'].isna() |
inventario['bodega'].isna()
].copy()

In [8]:
def motivo(row):
  motivos = []

  if pd.isna(row['id_inventario']):
   motivos.append("id_invalido")

  if pd.isna(row['id_producto']):
   motivos.append("producto_vacio")

  if pd.isna(row['stock']):
   motivos.append("stock_invalido")

  if pd.isna(row['bodega']):
   motivos.append("bodega_vacia")

  return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [9]:

validos.to_csv("inventario_curated.csv", index=False)
rechazados.to_csv("inventario_rejects.csv", index=False)

In [10]:
url_inventario = "https://raw.githubusercontent.com/kevinnumanzor17/etl-data-pipeline-2522192022/refs/heads/main/data/raw/B_inventario.csv"

In [11]:
inventario = pd.read_csv(url_inventario)

In [12]:
inventario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_inventario  186 non-null    object
 1   id_producto    180 non-null    object
 2   stock          181 non-null    object
 3   bodega         186 non-null    object
dtypes: object(4)
memory usage: 5.9+ KB

In [13]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [14]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16")

In [15]:
engine.connect()

In [16]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [17]:
import pandas as pd
from sqlalchemy import create_engine

In [18]:
DATABASE_URL = "postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16"

engine = create_engine(DATABASE_URL)

In [19]:
engine.connect()