In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/kevinnumanzor17/etl-data-pipeline-2522192022/refs/heads/main/data/raw/B_proveedores.csv"

df = pd.read_csv(url)

df.head()

  id_proveedor              proveedor         pais
0         P300             SurtiMax 0    Guatemala
1         P301     Insumos Globales 1   Costa Rica
2         P302  Distribuidora Atlas 2  El Salvador
3         P303          TecnoSupply 3    Guatemala
4         P304     Insumos Globales 4    Guatemala

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_proveedor  38 non-null     object
 1   proveedor     38 non-null     object
 2   pais          38 non-null     object
dtypes: object(3)
memory usage: 1.0+ KB

id_proveedor    0
proveedor       0
pais            0
dtype: int64

In [4]:
import pandas as pd

proveedores = df.copy()

# limpiar nombres de columnas
proveedores.columns = proveedores.columns.str.strip().str.lower()

# limpiar espacios
for col in proveedores.select_dtypes(include='object').columns:
  proveedores[col] = proveedores[col].astype(str).str.strip()

# convertir vacíos en null
proveedores = proveedores.replace(r'^\s*$', pd.NA, regex=True)

# eliminar duplicados
proveedores = proveedores.drop_duplicates()

In [5]:
# formato
proveedores['proveedor'] = proveedores['proveedor'].str.title()
proveedores['pais'] = proveedores['pais'].str.title()

In [6]:
validos = proveedores[
proveedores['id_proveedor'].notna() &
proveedores['proveedor'].notna() &
proveedores['pais'].notna()
].copy()

rechazados = proveedores[
proveedores['id_proveedor'].isna() |
proveedores['proveedor'].isna() |
proveedores['pais'].isna()
].copy()

In [7]:
def motivo(row):
   motivos = []

   if pd.isna(row['id_proveedor']):
    motivos.append("id_proveedor_vacio")

   if pd.isna(row['proveedor']):
    motivos.append("nombre_vacio")

   if pd.isna(row['pais']):
    motivos.append("pais_vacio")

   return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
validos.to_csv("B_proveedores_curated.csv", index=False)
rechazados.to_csv("B_proveedores_rejects.csv", index=False)

In [9]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [10]:
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://etl_seguros_sv16_user:Vy0ZyXr4fLTsi8331IIfURfJAZQA5MuA@dpg-d6qu81fkijhs73bd04dg-a.oregon-postgres.render.com/etl_seguros_sv16"

engine = create_engine(DATABASE_URL)

engine.connect()

In [11]:
from sqlalchemy import text

with engine.connect() as conn:
  conn.execute(text("""
CREATE TABLE IF NOT EXISTS proveedores (
id_proveedor VARCHAR(10) PRIMARY KEY,
proveedor VARCHAR(150),
pais VARCHAR(100)
);
"""))

conn.commit()

print("Tabla creada correctamente")

Tabla creada correctamente

In [12]:
validos.to_sql(
"proveedores",
engine,
if_exists="append",
index=False
)

35

In [13]:
import pandas as pd

pd.read_sql("SELECT * FROM proveedores LIMIT 10;", engine)

  id_proveedor              proveedor         pais
0         P300             Surtimax 0    Guatemala
1         P301     Insumos Globales 1   Costa Rica
2         P302  Distribuidora Atlas 2  El Salvador
3         P303          Tecnosupply 3    Guatemala
4         P304     Insumos Globales 4    Guatemala
5         P305          Tecnosupply 5  El Salvador
6         P306             Compured 6  El Salvador
7         P307            Ofimarket 7  El Salvador
8         P308       Papelera Unión 8    Guatemala
9         P309             Compured 9    Guatemala